# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YJBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
pod 'Masonry'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'ReactiveObjC', '3.1.0'
pod 'JLRoutes', '2.0.5'
pod 'YYKit'

pod 'IQKeyboardManager', '6.2.0'
pod 'LSSafeProtector'
pod 'ZFPlayer'
pod 'ZFPlayer/ControlView'
pod 'ZFPlayer/AVPlayer'
pod 'ZFPlayer/ijkplayer'
#pod 'Realm'
end
